import { Inter, Roboto } from 'next/font/google'
import Navigation from '../components/Navigation'
import './external.scss'
import './globals.scss'
import Footer from '@/components/Footer'
import Script from 'next/script'
import ClientLayout from '@/components/ClientLayout'
import TermlyScriptLoader from '@/components/TermlyScriptLoader'
import GoogleAnalyticsLoader from '@/components/GoogleAnalyticsLoader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="https://res.cloudinary.com/njh101010/image/upload/v1745678601/checkmirrors/website/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="https://res.cloudinary.com/njh101010/image/upload/v1745678601/checkmirrors/website/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="https://res.cloudinary.com/njh101010/image/upload/v1745678601/checkmirrors/website/favicon/favicon-16x16.png" />
        <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/njh101010/image/upload/v1745678601/checkmirrors/website/favicon/favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#ffffff" />
        <TermlyScriptLoader />
        <Script
          src="https://kit.fontawesome.com/c26d8f910e.js"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <GoogleAnalyticsLoader />
        <ClientLayout>
          <Navigation />
          {children}
          <Footer />
        </ClientLayout>
      </body>
    </html>
  )
} 